export { AboutComponent } from "./about/about.component"
export { PortafolioComponent } from "./portafolio/portafolio.component"
export { ProductoComponent } from "./producto/producto.component"
export { SearchComponent } from "./search/search.component"
export { LoginFormComponent } from "./login-form/login-form.component"
export { BookFormComponent } from "./book-form/book-form.component"
export { TableFormComponent } from "./table-form/table-form.component"
export { DatatablesComponent } from "./datatables/datatables.component"
